# =========================
# H2 DATABASE CONFIGURATION
# =========================
spring.datasource.url=jdbc:h2:file:./data/internshipdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show SQL in console
spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# JPA & HIBERNATE SETTINGS
# =========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Ensures data.sql is executed after schema creation
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JSearch API Key
jsearch.api.key=dc727e0feamsh8cd032857b3e571p11df78jsne2b384df91d8

gemini.api.key=AIzaSyB5YapI-3TbqU_hiJD0OuMlnwUVwFEpFQI
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent



